branches:
  only:
  - master
  - development

language: python
python:
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt


script: source/release_scripts/release.sh



deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "premium-plugins-bucket"
  skip_cleanup: true
  local_dir: release