language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - cd /
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install
  - cd -

script:
  - source/release_scripts/release.sh

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "core-framework-bucket"
  skip_cleanup: true
  local_dir: source/release_scripts/release
  region: eu-central-1

after_deploy:
  - source/release_scripts/update_version.sh
  - source/release_scripts/clear_bucket.sh

branches:
  only:
  - master