version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0.0

jobs:
  build-and-deploy:
    - run:
        name: Install AWS CLI
        command: sudo pip install awscli
    - run:
        name: Clear S3 Bucket
        command: sudo bash source/release_scripts/clear_bucket.sh
    - run:
        name: Build the release archive
        command: sudo bash source/release_scripts/release.sh
    - run:
        name: Upload to S3
        command: aws s3 sync release_scripts/release/*.tar.gz s3://
    - run:
        name: Update the latest version
        command: sudo bash source/release_scripts/update_version.sh

workflows:
  main:
    jobs:
      - build-and-deploy
