version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0.0

jobs:
  build-and-deploy:
    machine:
      image: ubuntu-1604:202010-01
    steps: 
      - run:
          name: test
          command: ls /home/circleci && ls /home/ubuntu 
      - run:
          name: Install AWS CLI
          command: sudo pip install awscli
      - run:
          name: Clear S3 Bucket
          command: sudo bash source/release_scripts/clear_bucket.sh
      - run:
          name: Build the release archive
          command: sudo bash source/release_scripts/release.sh
      - run:
          name: Upload to S3
          command: |
                    aws s3 sync source/release_scripts/release/*.tar.gz s3://
                    exit $?
      - run:
          name: Update the latest version
          command: sudo bash source/release_scripts/update_version.sh
          when: on_success

workflows:
  main:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - master
                - development