version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0.0

jobs:
  build-and-deploy:
    machine:
      image: ubuntu-1604:202010-01
    working_directory: ~/repo
    steps: 
      - checkout
      - run:
          name: Install AWS CLI
          command: sudo pip install awscli
      - run:
          name: Clear S3 Bucket
          command: sudo -E bash source/release_scripts/clear_bucket.sh
      - run:
          name: Build and Upload to S3
          command: |
                    sudo -E bash source/release_scripts/release.sh
                    ls source/release_scripts/release/
                    aws s3 sync source/release_scripts/release/*.tar.gz s3://core-framework-bucket/
                    exit $?
      - run:
          name: Update the latest version
          command: sudo -E bash source/release_scripts/update_version.sh
          when: on_success

workflows:
  main:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - master