version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0.0

jobs:
  build-and-deploy:
    machine:
      image: ubuntu-1604:202010-01
    working_directory: ~/repo
    steps: 
      - checkout
      - run:
          name: Install AWS CLI
          command: sudo pip install awscli
      - run:
          Name: Install Git
          command: sudo apt install git
      - run:
          name: Clone Heimdall Framework Releaser Script
          command: cd .. && git clone <RELEASER URL> && cd ..
      - run:
          name: Release
          command: sudo -E python3 releaser/releaser.py

workflows:
  main:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - master